import SwiftUI

struct ListCategoryView: View {
    @StateObject var listCategoryViewModel = ListCategoryViewModel()
    @Environment(\.presentationMode) var presentationMode: Binding<PresentationMode>
    var body: some View {
        VStack {
            VStack(alignment: .leading, spacing: 0) {
                HStack {
                    HStack {
                        Image("img_lefticon")
                            .resizable()
                            .frame(width: getRelativeWidth(size: 24.0), height: getRelativeHeight(size: 24.0), alignment: .center)
                            .scaledToFit()
                            .clipped()
                        Text(StringConstants.kLblCategory)
                            .font(FontScheme.kPoppinsBold(size: getRelativeHeight(size: 16.0)))
                            .foregroundColor(ColorConstants.Indigo900)
                            .minimumScaleFactor(0.5)
                            .multilineTextAlignment(.leading)
                            .frame(width: getRelativeWidth(size: 81.0), height: getRelativeHeight(size: 24.0), alignment: .topLeading)
                            .padding(.leading, getRelativeWidth(size: 12.0))
                    }
                    .frame(width: getRelativeWidth(size: 117.0), height: getRelativeHeight(size: 24.0), alignment: .leading)
                    .padding(.leading, getRelativeWidth(size: 16.0))
                    .padding(.trailing, getRelativeWidth(size: 242.0))
                }
                .frame(width: UIScreen.main.bounds.width - 20, height: getRelativeHeight(size: 24.0), alignment: .leading)
                ScrollView(.vertical, showsIndicators: false) {
                    VStack(alignment: .leading, spacing: 0) {
                        Group {
                            HStack {
                                Image("img_shirticon")
                                    .resizable()
                                    .frame(width: getRelativeWidth(size: 24.0), height: getRelativeHeight(size: 24.0), alignment: .center)
                                    .scaledToFit()
                                    .clipped()
                                    .padding(.vertical, getRelativeHeight(size: 16.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                Text(StringConstants.kLblShirt)
                                    .font(FontScheme.kPoppinsBold(size: getRelativeHeight(size: 12.0)))
                                    .foregroundColor(ColorConstants.LightBlueA200)
                                    .minimumScaleFactor(0.5)
                                    .multilineTextAlignment(.leading)
                                    .frame(width: getRelativeWidth(size: 32.0), height: getRelativeHeight(size: 18.0), alignment: .topLeading)
                                    .padding(.vertical, getRelativeHeight(size: 19.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                    .padding(.trailing, getRelativeWidth(size: 287.0))
                            }
                            .frame(width: UIScreen.main.bounds.width, height: getRelativeHeight(size: 56.0), alignment: .leading)
                            .background(ColorConstants.WhiteA700)
                            HStack {
                                Image("img_bikiniicon_1")
                                    .resizable()
                                    .frame(width: getRelativeWidth(size: 24.0), height: getRelativeHeight(size: 24.0), alignment: .center)
                                    .scaledToFit()
                                    .clipped()
                                    .padding(.vertical, getRelativeHeight(size: 16.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                Text(StringConstants.kLblBikini)
                                    .font(FontScheme.kPoppinsBold(size: getRelativeHeight(size: 12.0)))
                                    .foregroundColor(ColorConstants.Indigo900)
                                    .minimumScaleFactor(0.5)
                                    .multilineTextAlignment(.leading)
                                    .frame(width: getRelativeWidth(size: 37.0), height: getRelativeHeight(size: 18.0), alignment: .topLeading)
                                    .padding(.vertical, getRelativeHeight(size: 19.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                    .padding(.trailing, getRelativeWidth(size: 282.0))
                            }
                            .frame(width: UIScreen.main.bounds.width, height: getRelativeHeight(size: 56.0), alignment: .leading)
                            .background(ColorConstants.Blue50)
                            HStack {
                                Image("img_dressicon_1")
                                    .resizable()
                                    .frame(width: getRelativeWidth(size: 24.0), height: getRelativeHeight(size: 24.0), alignment: .center)
                                    .scaledToFit()
                                    .clipped()
                                    .padding(.vertical, getRelativeHeight(size: 16.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                Text(StringConstants.kLblDress)
                                    .font(FontScheme.kPoppinsBold(size: getRelativeHeight(size: 12.0)))
                                    .foregroundColor(ColorConstants.Indigo900)
                                    .minimumScaleFactor(0.5)
                                    .multilineTextAlignment(.leading)
                                    .frame(width: getRelativeWidth(size: 37.0), height: getRelativeHeight(size: 18.0), alignment: .topLeading)
                                    .padding(.vertical, getRelativeHeight(size: 19.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                    .padding(.trailing, getRelativeWidth(size: 282.0))
                            }
                            .frame(width: UIScreen.main.bounds.width, height: getRelativeHeight(size: 56.0), alignment: .leading)
                            .background(ColorConstants.WhiteA700)
                            HStack {
                                Image("img_manbagicon")
                                    .resizable()
                                    .frame(width: getRelativeWidth(size: 24.0), height: getRelativeHeight(size: 24.0), alignment: .center)
                                    .scaledToFit()
                                    .clipped()
                                    .padding(.vertical, getRelativeHeight(size: 16.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                Text(StringConstants.kLblWorkEquipment)
                                    .font(FontScheme.kPoppinsBold(size: getRelativeHeight(size: 12.0)))
                                    .foregroundColor(ColorConstants.Indigo900)
                                    .minimumScaleFactor(0.5)
                                    .multilineTextAlignment(.leading)
                                    .frame(width: getRelativeWidth(size: 110.0), height: getRelativeHeight(size: 18.0), alignment: .topLeading)
                                    .padding(.vertical, getRelativeHeight(size: 19.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                    .padding(.trailing, getRelativeWidth(size: 209.0))
                            }
                            .frame(width: UIScreen.main.bounds.width, height: getRelativeHeight(size: 56.0), alignment: .leading)
                            .background(ColorConstants.WhiteA700)
                            HStack {
                                Image("img_manpantsicon_1")
                                    .resizable()
                                    .frame(width: getRelativeWidth(size: 24.0), height: getRelativeHeight(size: 24.0), alignment: .center)
                                    .scaledToFit()
                                    .clipped()
                                    .padding(.vertical, getRelativeHeight(size: 16.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                Text(StringConstants.kLblManPants)
                                    .font(FontScheme.kPoppinsBold(size: getRelativeHeight(size: 12.0)))
                                    .foregroundColor(ColorConstants.Indigo900)
                                    .minimumScaleFactor(0.5)
                                    .multilineTextAlignment(.leading)
                                    .frame(width: getRelativeWidth(size: 70.0), height: getRelativeHeight(size: 18.0), alignment: .topLeading)
                                    .padding(.vertical, getRelativeHeight(size: 19.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                    .padding(.trailing, getRelativeWidth(size: 249.0))
                            }
                            .frame(width: UIScreen.main.bounds.width, height: getRelativeHeight(size: 56.0), alignment: .leading)
                            .background(ColorConstants.WhiteA700)
                            HStack {
                                Image("img_manshoesmanic")
                                    .resizable()
                                    .frame(width: getRelativeWidth(size: 24.0), height: getRelativeHeight(size: 24.0), alignment: .center)
                                    .scaledToFit()
                                    .clipped()
                                    .padding(.vertical, getRelativeHeight(size: 16.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                Text(StringConstants.kLblManShoes)
                                    .font(FontScheme.kPoppinsBold(size: getRelativeHeight(size: 12.0)))
                                    .foregroundColor(ColorConstants.Indigo900)
                                    .minimumScaleFactor(0.5)
                                    .multilineTextAlignment(.leading)
                                    .frame(width: getRelativeWidth(size: 71.0), height: getRelativeHeight(size: 18.0), alignment: .topLeading)
                                    .padding(.vertical, getRelativeHeight(size: 19.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                    .padding(.trailing, getRelativeWidth(size: 248.0))
                            }
                            .frame(width: UIScreen.main.bounds.width, height: getRelativeHeight(size: 56.0), alignment: .leading)
                            .background(ColorConstants.WhiteA700)
                            HStack {
                                Image("img_manunderweari_1")
                                    .resizable()
                                    .frame(width: getRelativeWidth(size: 24.0), height: getRelativeHeight(size: 24.0), alignment: .center)
                                    .scaledToFit()
                                    .clipped()
                                    .padding(.vertical, getRelativeHeight(size: 16.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                Text(StringConstants.kLblManUnderwear)
                                    .font(FontScheme.kPoppinsBold(size: getRelativeHeight(size: 12.0)))
                                    .foregroundColor(ColorConstants.Indigo900)
                                    .minimumScaleFactor(0.5)
                                    .multilineTextAlignment(.leading)
                                    .frame(width: getRelativeWidth(size: 105.0), height: getRelativeHeight(size: 18.0), alignment: .topLeading)
                                    .padding(.vertical, getRelativeHeight(size: 19.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                    .padding(.trailing, getRelativeWidth(size: 214.0))
                            }
                            .frame(width: UIScreen.main.bounds.width, height: getRelativeHeight(size: 56.0), alignment: .leading)
                            .background(ColorConstants.WhiteA700)
                            HStack {
                                Image("img_tshirticon")
                                    .resizable()
                                    .frame(width: getRelativeWidth(size: 24.0), height: getRelativeHeight(size: 24.0), alignment: .center)
                                    .scaledToFit()
                                    .clipped()
                                    .padding(.vertical, getRelativeHeight(size: 16.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                Text(StringConstants.kLblManTShirt)
                                    .font(FontScheme.kPoppinsBold(size: getRelativeHeight(size: 12.0)))
                                    .foregroundColor(ColorConstants.Indigo900)
                                    .minimumScaleFactor(0.5)
                                    .multilineTextAlignment(.leading)
                                    .frame(width: getRelativeWidth(size: 78.0), height: getRelativeHeight(size: 18.0), alignment: .topLeading)
                                    .padding(.vertical, getRelativeHeight(size: 19.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                    .padding(.trailing, getRelativeWidth(size: 241.0))
                            }
                            .frame(width: UIScreen.main.bounds.width, height: getRelativeHeight(size: 56.0), alignment: .leading)
                            .background(ColorConstants.WhiteA700)
                        }
                        Group {
                            HStack {
                                Image("img_womanbagicon_1")
                                    .resizable()
                                    .frame(width: getRelativeWidth(size: 24.0), height: getRelativeHeight(size: 24.0), alignment: .center)
                                    .scaledToFit()
                                    .clipped()
                                    .padding(.vertical, getRelativeHeight(size: 16.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                Text(StringConstants.kLblWomanBag)
                                    .font(FontScheme.kPoppinsBold(size: getRelativeHeight(size: 12.0)))
                                    .foregroundColor(ColorConstants.Indigo900)
                                    .minimumScaleFactor(0.5)
                                    .multilineTextAlignment(.leading)
                                    .frame(width: getRelativeWidth(size: 80.0), height: getRelativeHeight(size: 18.0), alignment: .topLeading)
                                    .padding(.vertical, getRelativeHeight(size: 19.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                    .padding(.trailing, getRelativeWidth(size: 239.0))
                            }
                            .frame(width: UIScreen.main.bounds.width, height: getRelativeHeight(size: 56.0), alignment: .leading)
                            .background(ColorConstants.WhiteA700)
                            HStack {
                                Image("img_womanpantsico_1")
                                    .resizable()
                                    .frame(width: getRelativeWidth(size: 24.0), height: getRelativeHeight(size: 24.0), alignment: .center)
                                    .scaledToFit()
                                    .clipped()
                                    .padding(.vertical, getRelativeHeight(size: 16.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                Text(StringConstants.kLblWomanPants)
                                    .font(FontScheme.kPoppinsBold(size: getRelativeHeight(size: 12.0)))
                                    .foregroundColor(ColorConstants.Indigo900)
                                    .minimumScaleFactor(0.5)
                                    .multilineTextAlignment(.leading)
                                    .frame(width: getRelativeWidth(size: 93.0), height: getRelativeHeight(size: 18.0), alignment: .topLeading)
                                    .padding(.vertical, getRelativeHeight(size: 19.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                    .padding(.trailing, getRelativeWidth(size: 226.0))
                            }
                            .frame(width: UIScreen.main.bounds.width, height: getRelativeHeight(size: 56.0), alignment: .leading)
                            .background(ColorConstants.WhiteA700)
                            HStack {
                                Image("img_womanshoesico")
                                    .resizable()
                                    .frame(width: getRelativeWidth(size: 24.0), height: getRelativeHeight(size: 24.0), alignment: .center)
                                    .scaledToFit()
                                    .clipped()
                                    .padding(.vertical, getRelativeHeight(size: 16.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                Text(StringConstants.kLblHighHeels)
                                    .font(FontScheme.kPoppinsBold(size: getRelativeHeight(size: 12.0)))
                                    .foregroundColor(ColorConstants.Indigo900)
                                    .minimumScaleFactor(0.5)
                                    .multilineTextAlignment(.leading)
                                    .frame(width: getRelativeWidth(size: 70.0), height: getRelativeHeight(size: 18.0), alignment: .topLeading)
                                    .padding(.vertical, getRelativeHeight(size: 19.0))
                                    .padding(.leading, getRelativeWidth(size: 16.0))
                                    .padding(.trailing, getRelativeWidth(size: 249.0))
                            }
                            .frame(width: UIScreen.main.bounds.width, height: getRelativeHeight(size: 56.0), alignment: .leading)
                            .background(ColorConstants.WhiteA700)
                        }
                    }
                    .frame(width: UIScreen.main.bounds.width, alignment: .topLeading)
                }
                .padding(.top, getRelativeHeight(size: 28.0))
            }
            .frame(width: UIScreen.main.bounds.width, alignment: .topLeading)
            .background(ColorConstants.WhiteA700)
            .padding(.top, getRelativeHeight(size: 30.0))
            .padding(.bottom, getRelativeHeight(size: 10.0))
        }
        .frame(width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.height)
        .background(ColorConstants.WhiteA700)
        .ignoresSafeArea()
        .hideNavigationBar()
    }
}

struct ListCategoryView_Previews: PreviewProvider {
    static var previews: some View {
        ListCategoryView()
    }
}
